cc_library(
    name = "jna",
    visibility = ["//visibility:public"],

    srcs = [
      "jna.cc",
    ],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/core:tensorflow",
    ]
)

